MOUSEKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
SPLIT_KEYBOARD = yes
TAP_DANCE_ENABLE = yes

SRC += features/tap_dance.c
